** Boulder Mountainbike Alliance

**** [[http://bouldermountainbike.org/][Home]]

**** [[http://smarttrail.geozen.com/][SmartTrail for Android]]

** The SmartTrail project

This repository is for the development of the iOS version of the SmartTrail app.

*** To Do
**** Need automated unit tests!
**** Switch to ARC.
**** Need splash view, displayed at least when app is run the first time. It should stay up until initial data is downloaded.
***** WebClient:  Employ KVO to notify listeners. In particular, splash view needs to know when to hide.
**** Need map view as a tab, plus maps for trail detail view.
**** Need uploading of conditions
**** Need Favorites view.
**** Need Alerts view.
**** Conditions: Better rating image should replace the dots.
**** Need images for tab bar.
**** Web views:
***** Move labels and rating images into scroll view or web view.
***** Capture tapped links and redirect relevant ones to views in the app. Others should be brought up in Safari.

*** License (MIT)

*Copyright (C) 2011-2012 by Boulder Mountainbike Alliance. All rights reserved*

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
